api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^asso/(?P<association_name>\w+)/board_members.json$',
        'api.views.association_board_members_name'),
)

eistiens_net/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns(
    '',

    # Associations app
    url(r'^associations/', include('associations.urls')),

    # Events app
    url(r'^evenements/', include('events.urls')),

    # Profiles app
    url(r'^profils/', include('profiles.urls')),

    # Messages
    url(r'^messages/', include('messaging.urls')),

    # Schedules
    url(r'^edt/', include('schedule.urls')),

    # API
    url(r'^api/', include('api.urls')),

    # local
    url(r'^locaux/', include('rooms.urls')),

    # Jobs
    url(r'^jobs/', include('jobs.urls')),

    # Facts
    url(r'^facts/', include('facts.urls')),

    # Portal app
    url(r'^', include('portal.urls')),

    # Medias
    # ! FOR TEST SERVER ONLY !
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # Grapelli urls : admin panel template
    url(r'^grappelli/', include('grappelli.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

messaging/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^publics$', 'messaging.views.publicthreads'),
    url(r'^publics/(?P<thread_id>\w+)$', 'messaging.views.thread'),

    url(r'^prives$', 'messaging.views.privatethreads'),
    url(r'^prives_utilisateurs$', 'messaging.views.private_thread_users'),

    url(r'^trie$', 'messaging.views.users_trie'),
    url(r'^creer_conversation$', 'messaging.views.create_new_private_thread'),
    url(r'^supprimer_conversation', 'messaging.views.delete_private_thread'),
    url(r'^supprimer_toutes_conversations',
        'messaging.views.delete_all_private_threads'),

    url(r'^upload-image$', 'messaging.views.upload_image'),
)

messaging/models.py
# coding: utf-8

from django.contrib.auth.models import User
from django.db import models

import random, string, markdown2

from jobs.api import sanitize


class Thread(models.Model):

    """
    Threads are groups of messages.
    """

    subject = models.CharField("Thread object", max_length=100)

    timestamp = models.DateTimeField(
        "Creation date", auto_now_add=True, editable=False)

    last_message_date = models.DateTimeField(
        "Date du dernier message", auto_now_add=True, editable=True)

    views = models.PositiveIntegerField('Nombre de vues', default=0)

    creator = models.ForeignKey(User)

    def get_messages(self):
        """
        Returns the thread's messages.
        """
        return Message.objects.filter(message_type=0, parent_thread=self.id)

    def __unicode__(self):
        return u'%s (%s)' % (unicode(self.subject), unicode(self.timestamp))


class PrivateThread(models.Model):

    """
    Private conversation.
    """

    subject = models.CharField("PM object", max_length=100)

    crossbar_topic = models.CharField("Crossbar", max_length=255,
        blank=True, null=True, default='')

    timestamp = models.DateTimeField(
        "Creation date", auto_now_add=True, editable=False)

    last_message_date = models.DateTimeField(
        "Date du dernier message", auto_now_add=True, editable=True)

    participants = models.ManyToManyField(User)

    def get_messages(self):
        """
        Returns the conversation's messages.
        """
        return PrivateMessage.objects.filter(parent_thread=self.id)

    def save(self, *args, **kwargs):
        super(PrivateThread, self).save(*args, **kwargs)

        # If it is the first time, we generate the `crossbar_topic`
        if len(self.crossbar_topic) == 0:
            random_seed = ''.join(random.choice(string.ascii_uppercase) for _ in xrange(42))
            self.crossbar_topic = 'pvtopic_%d_%s' % (self.id, random_seed)
            super(PrivateThread, self).save(*args, **kwargs)


    def __unicode__(self):
        return u"[PM] %s (%s)" % (unicode(self.subject), unicode(self.timestamp))


class Message(models.Model):

    """
    Messages are the atoms present in a thread.
    """

    author = models.ForeignKey(User)

    content = models.TextField("Contenu du message", blank=True)

    markdown_content = models.TextField("Contenu du message (markdown)")

    timestamp = models.DateTimeField(
        "Redaction date", auto_now_add=True, editable=False)

    parent_thread = models.ForeignKey(Thread)

    def save(self, *args, **kwargs):
        self.content = markdown2.markdown(self.markdown_content)
        self.content = sanitize(self.content)
        super(Message, self).save(*args, **kwargs)

    def __unicode__(self):
        return u"%s (%s)" % (unicode(self.author), unicode(self.timestamp))


class PrivateMessage(models.Model):

    """
    Private messages are the atoms present in a private conversation.
    """

    author = models.ForeignKey(User)

    content = models.TextField("Contenu du message", max_length=2000)

    timestamp = models.DateTimeField(
        "Redaction date", auto_now_add=True, editable=False)

    parent_thread = models.ForeignKey(PrivateThread)

    def __unicode__(self):
        return u"%s (%s)" % (unicode(self.author), unicode(self.timestamp))

messaging/views.py
# coding: utf-8

from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.contrib.auth.models import User
from django.middleware import csrf

from messaging.api import create_private_thread, create_public_thread
from messaging.api import generate_image_filename, upload, generate_users_trie

from messaging.models import Thread, PrivateThread, PrivateMessage, Message
from profiles.models import Profile

import json
import os


@login_required
def privatethreads(request):
    """
    Displays all the private threads of the connected user.

    Can be used with a GET method to prepare the modal to start a new
    conversation: if the user clicks on 'Envoyer un message' on the profile
    of another user.

    :param request: request object
    """
    if request.method == 'GET' and 'destinataire' in request.GET:
        recipient = request.GET['destinataire']
    else:
        recipient = None

    try:
        profile = Profile.objects.get(user=request.user)
        profile.last_private_messages_check = timezone.now()
        profile.save()
    except:
        pass  # For instance, we are admin -> Maybe no profile

    threads = PrivateThread.objects.filter(
        participants=request.user).order_by('-last_message_date')

    return render_to_response(
        'private_thread.html',
        {
            'request': request,
            'threads': threads,
            'message_sent': 'eistiens.net.message.sent',
            'request_last_messages': 'eistiens.net.last_messages',
            'recipient': recipient
        }, context_instance=RequestContext(request))


@login_required
def publicthreads(request):
    """
    Displays the public threads to the user, sorted by last message date desc

    Handles POST request to create a new thread when the user clicks the
    "Nouveau thread" button.

    :param request: request object
    """
    error = False

    if request.method == 'POST':
        POST = request.POST

        result = {
            'redirect': reverse('messaging.views.publicthreads')
        }

        if all(x in POST for x in ('csrfmiddlewaretoken', 'subject', 'message')):
            csrf_token = POST['csrfmiddlewaretoken']
            subject, message = POST['subject'], POST['message']

            if csrf_token == csrf.get_token(request):
                thread = create_public_thread(subject, request.user, message)
                result['redirect'] = reverse('messaging.views.thread', args=(thread.id,))
        

        return HttpResponse(json.dumps(result), content_type="application/json")

    threads = Thread.objects.all().order_by('-last_message_date')

    return render_to_response(
        'threads.html',
        {
            'request': request,
            'threads': threads,
            'error': error
        }, context_instance=RequestContext(request))


@login_required
def thread(request, thread_id):
    """
    Displays a public thread

    :param request: request object
    :param thread_id: id of the thread to show
    """

    thread = get_object_or_404(Thread, id=thread_id)

    thread.views += 1
    thread.save()

    return render_to_response(
        'public_thread.html',
        {
            'request': request,
            'thread': thread,
            'send_message': 'eistiens.net.message.public'
        }, context_instance=RequestContext(request))


@login_required
def upload_image(request):
    result = {
        'success': True,
        'url': ''
    }

    if request.method == 'POST':
        FILES = request.FILES

        # Only allow images with size <= 5 MiB
        if 'image' not in FILES or FILES['image'].size > 5 * 1024 * 1024:
            result['success'] = False
            result['message'] = 'Aucune image ou image trop lourde (Max 5 Mo)'

        else:
            image = FILES['image']
            _, extension = os.path.splitext(image.name)

            if extension not in ('.jpg', '.jpeg', '.gif', '.png', '.bmp'):
                result['success'] = False
                result['message'] = 'Format %s non supporté' % extension

            else:
                path = 'img/messages'
                image_path, filename = generate_image_filename(image.name, path)
                upload(image_path, image)
                result['url'] = os.path.join('/media', path, filename)

    else:
        result['success'] = False
        result['message'] = 'Pas une requete POST'
    
    return HttpResponse(json.dumps(result), content_type="application/json")


@login_required
def private_thread_users(request):
    """
    Returns a JSON string containing the users in a given thread.
    """

    error = HttpResponse(json.dumps({ 'success': False }),
        content_type="application/json")

    if request.method != 'GET' or 'a' not in request.GET:
        return error

    # Get the content from the request
    crossbar_topic = request.GET['a']

    # Query the thread that corresponds to the given content
    if not PrivateThread.objects.filter(crossbar_topic=crossbar_topic).exists():
        return error

    thread = PrivateThread.objects.get(crossbar_topic=crossbar_topic)

    # The user has nothing to do here if it is not a participant of the thread
    if request.user not in thread.participants.all():
        return error

    # List the users
    users = [{
        'name': u.first_name + ' ' + u.last_name,
        'url': reverse('profiles.views.display_profile', args=(u.username,))
    } for u in thread.participants.all().order_by('first_name', 'last_name')]

    # JSON content that will be returned
    result = {
        'success': True,
        'users': users
    }

    return HttpResponse(json.dumps(result), content_type="application/json")


@login_required
@cache_page(60) ## TODO: Increase when more users will be in the DB ##
def users_trie(request):
    """
    Returns a trie containing all users in the database
    (first name + last name and last name + first name).
    """
    return HttpResponse(json.dumps(generate_users_trie()),
        content_type="application/json")


@login_required
def create_new_private_thread(request):
    """
    Creates a new private thread
    """
    if request.method == 'GET':
        subject = request.GET.get('subject', '')
        message = request.GET.get('message', '')
        recipients_strings = request.GET.get('recipients', '').split(',')
        csrf_token = request.GET.get('csrf', '')

        if csrf_token == csrf.get_token(request):
            recipients = []

            for recipient in recipients_strings:
                try:
                    recipients.append(User.objects.get(username=recipient))
                except: # User does not exist -> We have a jerk here
                    pass

            # Prevent bad request, happens if the user is a jerk
            if all(len(x) > 0 for x in (subject, message, recipients)):
                create_private_thread(
                    subject, request.user, recipients, message)

    return HttpResponse(json.dumps({
            'redirect': reverse('messaging.views.privatethreads'),

        }), content_type='application/json')


@login_required
def delete_private_thread(request):
    """
    Deletes a private thread from a user.
    """
    if request.method != 'GET':
        return HttpResponseRedirect(reverse('messaging.views.privatethreads'))

    csrf_token = request.GET.get('csrf', '')
    crossbar_topic = request.GET.get('a', '')

    if csrf_token != csrf.get_token(request):
        return HttpResponseRedirect(reverse('messaging.views.privatethreads'))

    if PrivateThread.objects.filter(crossbar_topic=crossbar_topic).exists():
        thread = PrivateThread.objects.get(crossbar_topic=crossbar_topic)

        if request.user in thread.participants.all():
            thread.participants.remove(request.user)

    return HttpResponseRedirect(reverse('messaging.views.privatethreads'))


@login_required
def delete_all_private_threads(request):
    """
    Deletes all private threads from a user.
    """
    if request.method != 'GET':
        return HttpResponseRedirect(reverse('messaging.views.privatethreads'))

    csrf_token = request.GET.get('csrf', '')

    if csrf_token != csrf.get_token(request):
        return HttpResponseRedirect(reverse('messaging.views.privatethreads'))

    for thread in PrivateThread.objects.filter(participants=request.user):
        thread.participants.remove(request.user)

    return HttpResponseRedirect(reverse('messaging.views.privatethreads'))

messaging/templates/public_thread.html
{% extends "base2.html" %}

{% block template-specific-css %}
<!-- Threads thumbnails CSS -->
<link href="/media/css/thread.css" rel="stylesheet">
<link href="/media/css/associations.css" rel="stylesheet">
{% endblock %}

{% block tooltip %}
<!-- Tooltip area -->
<div class="tooltip-area">
	<div class="container">
		<h1 class="text-center">Agora</h1>
	</div> 
</div><!-- /Tooltip area -->
{% endblock %}

{% block content-block %}

<div class="container container-on-top">

	<h2>{{ thread.subject }}</h2>

	<div class="row-fluid thread-first-message">
		<small>
			<table class="table table-responsive">
				<thead>
					<tr>
						<th class="thread-creation-date">Crée le</th>
						<th class="thread-last-message-first">Dernier message</th>
						<th class="thread-messages">Messages</th>
						<th class="thread-views">Vues</th>
					</tr>
				</thead>

				<tr>
					<th>{{ thread.message_set.all.0.timestamp }}</th>
					<th>{{ thread.last_message_date }}</th>
					<th><center>{{ thread.message_set.all|length }}</center></th>
					<th><center>{{ thread.views }}</center></th>
				</tr>
			</table>
		</small>
	</div>

	<div id="messages-list">
	{% for message in thread.message_set.all|dictsort:"timestamp" %}
		{% if forloop.first %}
		<hr>
		{% endif %}

		<div class="row"{% if not forloop.first %} style="margin-left: 1%;"{% endif %}>
			{% if forloop.first %}
			<div class="col-md-2 col-xs-2">
				<img class="thread-profile-picture" src="{{ message.author.profile.avatar.url }}">

				<div class="thread-message-center"> 
					<b>{{ message.author.first_name }} {{ message.author.last_name }}</b>
				</div>

				<hr>

				<div class="thread-message-center">
					<small style="color: grey">{{ message.timestamp|date:"d b Y H:i" }}</small>
				</div>
			</div>
			{% endif %}

			<div class="col-md-10 col-xs-9 thread-message">
				<div style="margin-left: 3%">
					{{ message.content|safe }}
				</div>
			</div>

			{% if not forloop.first %}
			<div class="col-md-2 col-xs-2">
				<img class="thread-profile-picture" src="{{ message.author.profile.avatar.url }}">

				<div class="thread-message-center"> 
					<b>{{ message.author.first_name }} {{ message.author.last_name }}</b>
				</div>

				<hr>

				<div class="thread-message-center">
					<small style="color: grey">{{ message.timestamp|date:"d b Y H:i" }}</small>
				</div>
			</div>
			{% endif %}
		</div>

		<hr>
	{% endfor %}
	</div>

	<div class="row-fluid">
		<h4>Répondre</h4>

		<textarea class="form-control" rows="3" id="message"></textarea>

		<button data-toggle="modal" data-target="#image-upload-modal">Image</button>
		<button class="btn btn-default pull-right" id="btn-send">Envoyer</button>
	</div>

</div>

<div class="modal fade" id="image-upload-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

				<h3 id="myModalLabel">Ajouter une image</h3>
			</div>
			<div class="modal-body">
				<form enctype="multipart/form-data" method="POST" action="{% url 'messaging.views.upload_image' %}" id="image-upload-form">
					{% csrf_token %}

					<div class="form-group">
						<label for="subject">Image</label>

						<input class="form-control" type="file" name="image">
					</div>

					<div class="form-actions">
						<button class="btn btn-primary" type="submit">Ajouter</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block template-specific-js %}

<script src="/media/js/autobahn.min.js"></script>
<script src="/media/js/eistiens-net.js"></script>
<script src="/media/js/jquery.form.js"></script>

<script>
	$('#image-upload-form').submit(function(e) {
		e.preventDefault();

		$('#image-upload-form').ajaxSubmit({
			resetForm: true,
			success: function(data) {
				if (data.success)
					$('#message').val($('#message').val() + '![image](' + data.url + ')');
				else
					alert(data.message);

				$('#image-upload-modal').modal('hide');
			}
		});

		return false;
	});

	function resize_images() {
		$('.thread-message img').each(function () {
			$(this).css('max-width', (window.innerWidth / 2) + 'px')
		});
	}

	resize_images();

	window.onresize = resize_images;

	var connection = newConnection();

	connection.onopen = function(session, details) {
		function on_message(data) {
			message = JSON.parse(data);

			console.log(message.user);

			obj = $('#messages-list');

			obj.append(
				'<div class="row" style="margin-left: 1%">' +
				'	<div class="col-md-10 col-xs-9 thread-message">' +
				'		<div style="margin-left: 3%">' +
				'			' + message.content + 
				'		</div>' +
				'	</div>' +
				'	<div class="col-md-2 col-xs-2">' +
				'		<img class="thread-profile-picture" src="' + message.user.picture + '">' +
				'		<div class="thread-message-center">' +
				'			<b>' + message.user.name + '</b>' +
				'		</div>' +
				'		<hr>' +
				'		<div class="thread-message-center">' +
				'			<small style="color: grey">' + message.timestamp + '</small>' +
				'		</div>' +
				'	</div>' +
				'</div>' +
				'<hr>');

			resize_images();
		}

		session.subscribe("pb_thread_{{ thread.id }}", on_message).then(
			function (sub) { console.log('subscribed to topic 1'); },
			function (err) { console.log('failed to subscribe to topic 1', err); }
		);

		$('#btn-send').click(function() {
			message = $('#message').val();

			if (message.length > 0) {
				json_string = JSON.stringify({"a": "{{ csrf_token }}", "b": "{{ request.user.id }}", "c": message, "d": "{{ thread.id }}"});

				session.publish('{{ send_message }}', [json_string]);

				$('#message').val('');
			}
		});
	}

	connection.onclose = function(reason, details) { }

	connection.open();
</script>

{% endblock %}

messaging/templates/threads.html
{% extends "base2.html" %}

{% block template-specific-css %}
<!-- Threads thumbnails CSS -->
<link href="/media/css/thread.css" rel="stylesheet">
<link href="/media/css/associations.css" rel="stylesheet">
{% endblock %}

{% block tooltip %}
<!-- Tooltip area -->
<div class="tooltip-area">
	<div class="container">
		<h1 class="text-center">Agora</h1>
	</div> 
</div><!-- /Tooltip area -->
{% endblock %}

{% block content-block %}

{% if error %}
<div class="alert alert-success">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	Une erreur est survenue lors de la création du nouveau thread,
	peut-être n'as-tu pas rempli tous les champs ?
</div>
{% endif %}

<div class="container container-on-top">

	<button id="btn-new-thread" class="btn btn-default">
		Nouveau thread
	</button>

	<div id="new-thread-div" style="display: none">
		<div>
			<button class="close btn-dismiss">×</button>

			<h3>Créer un nouveau thread</h3>
		</div>

		<div class="modal-body">
			<fieldset>
				<input type="hidden" value="{{ csrf_token }}" id="csrf">

				<div class="form-group">
					<label for="subject">Sujet</label>

					<input class="form-control" id="subject">
				</div>

				<div class="form-group">
					<label for="subject">Message <button data-toggle="modal" data-target="#image-upload-modal">Image</button></label>

					<textarea class="form-control" rows="3" id="message"></textarea>
				</div>

				<div class="pull-right">
					<button class="btn btn-primary" type="submit" id="create-thread">Créer</button>
					<a class="btn btn-dismiss">Annuler</a>
				</div>
			</fieldset>
		</div>
		<hr>
	</div>

	<table class="table table-striped table-responsive">
		<thead>
			<tr>
				<th class="thread-subject">Sujet</th>
				<th class="thread-messages">Messages</th>
				<th class="thread-views">Vues</th>
				<th class="thread-last-message">Dernier message</th>
			</tr>
		</thead>

		<tbody id="thread-body">
			{% for thread in threads %}
			<tr>
				<td>
					<a href="{% url 'messaging.views.thread' thread.id %}">{{ thread.subject }}</a>
				</td>

				<td class="text-center">
					{{ thread.message_set.all|length }}
				</td>

				<td class="text-center">
					{{ thread.views }}
				</td>

				<td>
					{{ thread.last_message_date|date:"d F Y H:i" }}
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>

</div>

<div class="modal fade" id="image-upload-modal" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

				<h3 id="myModalLabel">Ajouter une image</h3>
			</div>
			<div class="modal-body">
				<form enctype="multipart/form-data" method="POST" action="{% url 'messaging.views.upload_image' %}" id="image-upload-form">
					{% csrf_token %}

					<div class="form-group">
						<label for="subject">Image</label>

						<input class="form-control" type="file" name="image">
					</div>

					<div class="form-actions">
						<button class="btn btn-primary" type="submit">Ajouter</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock content-block %}

{% block template-specific-js %}

<script src="/media/js/jquery.form.js"></script>

<script>
	$('#btn-new-thread').click(function() {
		$('#new-thread-div').slideDown();
		$('#btn-new-thread').hide();
	});

	$('.btn-dismiss').click(function() {
		$('#new-thread-div').slideUp();
		$('#btn-new-thread').fadeIn();
	});

	$('#image-upload-form').submit(function(e) {
		e.preventDefault();

		$('#image-upload-form').ajaxSubmit({
			resetForm: true,
			success: function(data) {
				if (data.success)
					$('#message').val($('#message').val() + '![image](' + data.url + ')');
				else
					alert(data.message);

				$('#image-upload-modal').modal('hide');
			}
		});

		return false;
	});

	$('#create-thread').click(function() {
		csrf = $('#csrf').val();
		subject = $('#subject').val();
		message = $('#message').val();

		$.post("{% url 'messaging.views.publicthreads' %}",
            {
                'subject': subject,
                'message': message,
                'csrfmiddlewaretoken': csrf
            },
            function(data) { window.location.href = data.redirect; }
        );
	})
</script>

{% endblock %}