api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^asso/(?P<association_name>\w+)/board_members.json$',
        'api.views.association_board_members_name'),
)

eistiens_net/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns(
    '',

    # Associations app
    url(r'^associations/', include('associations.urls')),

    # Events app
    url(r'^evenements/', include('events.urls')),

    # Profiles app
    url(r'^profils/', include('profiles.urls')),

    # Messages
    url(r'^messages/', include('messaging.urls')),

    # Schedules
    url(r'^edt/', include('schedule.urls')),

    # API
    url(r'^api/', include('api.urls')),

    # local
    url(r'^locaux/', include('rooms.urls')),

    # Jobs
    url(r'^jobs/', include('jobs.urls')),

    # Facts
    url(r'^facts/', include('facts.urls')),

    # Portal app
    url(r'^', include('portal.urls')),

    # Medias
    # ! FOR TEST SERVER ONLY !
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # Grapelli urls : admin panel template
    url(r'^grappelli/', include('grappelli.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

profiles/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^annuaire$', 'profiles.views.users_directory'),

    url(r'^(?P<username>\w+)/$', 'profiles.views.display_profile'),
    url(r'^(?P<username>\w+)/edit$', 'profiles.views.edit_profile'),

    url(r'^mes_assos$', 'profiles.views.my_associations'),
    url(r'^mes_evenements$', 'profiles.views.my_events'),
)

profiles/models.py
# coding: utf-8

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models

from messaging.models import PrivateThread

from datetime import datetime


class Profile(models.Model):
    """
    A profile contains all additional information associated with a user.

    It is a convenient place to store any information about the site's users
    and that doesn't fit into the default User model, such as social network
    profiles, website adress or even a profile image.
    To access a profile from a user objet, simply use 'user.profile'.
    """

    user = models.OneToOneField(User, verbose_name="Utilisateur")

    STATUS = (
        (0, "Personnel EISTI"),
        (1, "Professeur"),
        # Status 2 to 4 are available for future use
        (5, "CPI 1"),
        (6, "CPI 2"),
        (7, "ING 1"),
        (8, "ING 2"),
        (9, "ING 3"),
        (10, "Master"),
        (11, "Ancien"),
    )
    status = models.SmallIntegerField(
        "Promotion ou fonction", choices=STATUS, blank=True, null=True)

    pseudo = models.CharField(
        "Pseudonyme", max_length=100, blank=True, null=True)

    avatar = models.ImageField(
        "Avatar de l'utilisateur",
        upload_to='img/users/avatars/',
        default='img/users/default_avatar_128.png')

    bio = models.TextField("Présentation", blank=True, null=True)

    birthdate = models.DateField(
        "Date de naissance", blank=True, null=True)

    # Social networks and websites
    linkedIN = models.URLField("URL profil LinkedIN", blank=True, null=True)

    viadeo = models.URLField("URL profil Viadeo", blank=True, null=True)

    twitter = models.URLField("URL profil Twitter", blank=True, null=True)

    facebook = models.URLField("URL profil Facebook", blank=True, null=True)

    google_plus = models.URLField("URL profil Google+", blank=True, null=True)

    website = models.URLField(
        "Site internet personnel", blank=True, null=True)

    # Last time the user checked his/her private messages
    last_private_messages_check = models.DateTimeField(
        'Derniere lecture des messages privés', auto_now_add=True)

    def __unicode__(self):
        return str(self.user) + " profile"

    def is_birthday(self):
        if self.birthdate is None:
            return False

        today = datetime.today()
        birth = self.birthdate

        return today.day == birth.day and today.month == birth.month

    def get_nb_messages(self):
        """
        Returns the number of received messages (archived or not) for a given
        user.
        """
        # return Message.objects.filter(user_to=self.user).count()
        return 0

    def get_nb_unread_messages(self):
        """
        Returns the number of unread/not archived messages for a given user.
        """
        return PrivateThread.objects.filter(participants=self.user,
            last_message_date__gt=self.last_private_messages_check).count()


@receiver(post_save, sender=User)
def new_user_handler(instance, created, **kwargs):
    """
    Event handler that creates a Profile each time a new user is created.

    This handler is called each time a user object is saved in the database.
    This could mean the user has been either created or updated. Thus a profile
    should only be created for new user objects.

    :param instance: newly created or modified user
    :param created: True if the user was created and not updated
    """

    if created and not instance.is_superuser:
        new_profile = Profile(user=instance)
        new_profile.save()

profiles/forms.py
from django import forms
from profiles.models import Profile
# from profiles.models import Message


class ProfileForm(forms.ModelForm):
    """
    ModelForm to edit a user profile (Profil model class).

    This form only exculdes the user field, for a profile cannot be attributed
    to another user. See the Profil model class for more details.
    """

    class Meta:
        model = Profile
        exclude = ['user', 'last_private_messages_check']

profiles/views.py
#coding: utf-8

"""
Views functions for the profils module.

Those views mostly deal with profile consultation and management along with
user parameters and settings, but also the internal messaging system.
"""

from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.template import RequestContext
from django.contrib import messages

from profiles.models import Profile
from profiles.forms import ProfileForm
from events.models import Registration
from associations.models import Member
from profiles.api import users_query

import json


def profiles_home(request):
    """
    Home page for profile module.

    :param request: request object
    """
    return render_to_response(
        "work_in_progress.html",
        {
            'request': request
        })



def display_profile(request, username):
    """
    Displays a user's profile.

    Public page that displays basic and profile informations relative to a
    given user.

    :param request: request object
    :param username: login name og the user whom profile is displayed
    """

    user = get_object_or_404(User, username=username)
    user_profile = get_object_or_404(Profile, user=user.id)

    # user's associations
    memberships = Member.objects.filter(user=user.id).order_by(
        '-year', 'status')

    return render_to_response(
        "profile.html",
        {
            'request': request,
            'user': user,
            'profile': user_profile,
            'memberships': memberships
        })


@login_required
def edit_profile(request, username):
    """
    Displays a form to edit the current user's profile.

    This page should only be assessible to the profile's owner. If the form is
    valid, the profile is updated and the view redirects to the profile
    consultation view.

    :param request: request object
    :param username: login name of the user whom profile is to be edited
    """

    user = get_object_or_404(User, username=username)
    # The following line should reject any illegitimate accesses :
    if request.user != user:
        raise PermissionDenied

    user_profile = get_object_or_404(Profile, user=user.id)

    profile_edition_form = ProfileForm(
        request.POST or None,
        request.FILES or None,
        instance=user_profile)

    if profile_edition_form.is_valid():
        profile_edition_form.save()
        messages.success(request, u'Votre profil a bien été mis à jour.')

    elif request.POST:
        messages.error(request, u'Erreur lors de la modification du profil.')

    return render_to_response(
        "profile_edition.html",
        {
            'request': request,
            'profile_edition_form': profile_edition_form,
        },
        context_instance=RequestContext(request))


@login_required
def my_associations(request):
    """
    Displays connected user's association memberships.

    This view displays all active as well as previous years association
    memberships.

    :param request: request object
    """

    memberships = Member.objects.filter(user=request.user)
    memberships.order_by('-year', 'status')

    return render_to_response(
        "mes_associations.html",
        {
            'request': request,
            'memberships': memberships
        })


@login_required
def my_events(request):
    """
    Displays connected user's events.

    This view displays all events to which the connected user has registered.

    :param request: request object
    """

    registrations = Registration.objects.filter(
        user=request.user.id).order_by('-event__day')

    future_events = [r.event for r in registrations if not r.event.is_past_event()]
    past_events = [r.event for r in registrations if r.event.is_past_event()]

    return render_to_response(
        "mes_evenements.html",
        {
            'request': request,
            'future_events': future_events,
            'past_events': past_events
        })


def users_directory(request):
    """
    Displays the directory containing all users, search can be performed.

    Can also make a query to let a user search other users in the database.

    :param request: request object
    """

    users = []
    first_name, last_name, status = '_', '_', '_'
    message = False

    birthdays = [b for b in Profile.objects.all() if b.is_birthday()]  # PAS BO

    if request.method == 'POST':
        first_name = request.POST.get('first_name', '_')
        last_name = request.POST.get('last_name', '_')
        status = request.POST.get('status', '_')

        if len(first_name) == 0:
            first_name = '_'

        if len(last_name) == 0:
            last_name = '_'

        users = users_query(request, first_name, last_name, status)
        users = json.loads(users.content)

        if len(users) == 0:
            message = True

        if status.isdigit():
            status = int(status)


    return render_to_response(
        "annuaire.html",
        {
            'request': request,
            'statuses': Profile.STATUS,
            'birthdays': birthdays,
            'users': users,
            'first_name': first_name,
            'last_name': last_name,
            'status': status,
            'message': message
        }, context_instance=RequestContext(request))

profiles/templates/annuaire.html
{% extends "base2.html" %}

{% block template-specific-css %}
<!-- Directory thumbnails CSS -->
<link href="/media/css/associations.css" rel="stylesheet">
{% endblock %}



{% block tooltip %}
<!-- Tooltip area -->
<div class="tooltip-area">
    <div class="container">
        <h1 class="text-center">Recherche sur l'annuaire</h1>
    </div> 
</div><!-- /Tooltip area -->
{% endblock %}


{% block content-block %}

<div class="container container-on-top">
	{% if birthdays %}
	<p>
		{% with birthdays|length as n_birthdays %}
			{{ n_birthdays }} anniversaire{{ n_birthdays|pluralize }} aujourd'hui : 
		{% endwith %}

		{% for profile in birthdays %}
			<a href="{% url 'profiles.views.display_profile' profile.user.username %}">{{ profile.user.first_name }} {{ profile.user.last_name }}</a>{% if not forloop.last %},{% endif %}
		{% endfor %}
	</p>
	{% endif %}




	{% if message %}
	<div class="alert alert-warning">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		Aucun résultat trouvé !
	</div>
	{% endif %}

	<div class="well">
		<div class="row-fluid">
			<form method="POST" class="form-horizontal" action="{% url 'profiles.views.users_directory' %}" class="input-append offset3" style="margin-top:18px;">
				{% csrf_token %}

				<div class="form-group">
					<div class="col-md-2 col-sm-4 col-xs-4">
						<label class="control-label">Prénom</label>
					</div>

					<div class="col-md-3 col-sm-6 col-xs-6">
						<input class="form-control" type="text" name="first_name" {% if first_name !=  '_' %}value="{{ first_name }}" {% endif %}placeholder="Laisser vide si non connu">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-2 col-sm-4 col-xs-4">
						<label class="control-label">Nom</label>
					</div>

					<div class="col-md-3 col-sm-6 col-xs-6">
						<input class="form-control" type="text" name="last_name" {% if last_name !=  '_' %}value="{{ last_name }}" {% endif %}placeholder="Laisser vide si non connu">
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-2 col-sm-4 col-xs-4">
						<label class="control-label">Promotion / Fonction</label>
					</div>
					
					<div class="col-md-3 col-sm-6 col-xs-6">
						<select name="status" class="form-control">
							<option value="_">---</option>
							{% for s in statuses %}
							<option value="{{ s.0 }}" {% if status == s.0 %}selected{% endif %}>{{ s.1 }}</option>
							{% endfor %}
						</select>
					</div>
				</div>

				<button class="btn btn-default" type="submit">Trouver un eistien</button>
			</form>
		</div>
	</div>

	{% if users %}
	<div class="well">
		<p>{{ users|length }} membre{{ users|length|pluralize }}</p>

		{% for user in users %}
		{% if forloop.counter0|divisibleby:6 %}
		<div class="row">
		{% endif %}

		<div class="col-md-2 col-sm-4">
			<div class="thumbnail mini-thumbnail">

				<img src="{{ user.picture }}" alt="profile picture" class="profile-picture">

				<a href="{% url 'profiles.views.display_profile' user.username %}">
					<div class="caption" style="text-align: center">
						<h5>{{ user.first_name }} {{ user.last_name }}</h5>
					</div>
				</a>

				<div class="clearfix"></div>
			</div>
		</div>

		{% if forloop.counter|divisibleby:6 or forloop.last %}
		</div>
		{% endif %}
		{% endfor %}
	</div>
	{% endif %}
</div>
{% endblock %}

{% block template-specific-js %}
<script>
$(document).ready( function() {
    // Links on profile pictures
    $('.profile-picture').click( function(){
        window.location.href=$(this).next('a').attr('href');
    });
});
</script>
{% endblock %}

profiles/templates/mes_associations.html
{% extends "base2.html" %}

{% block template-specific-css %}
<!-- Assocation thumbnails CSS -->
<link href="/media/css/associations.css" rel="stylesheet">
{% endblock %}

{% block content-block %}

<div class="tooltip-area">
    <div class="container">
        <h1 class="text-center">Mes associations</h1>
    </div> 
</div><!-- /Tooltip area -->


<div class="container container-on-top">


    <div class="row">
    {% for membership in memberships %}

        {% ifchanged membership.year %}
        <h4 class="user-membership-year col-md-12 col-sm-12 col-xs-12">
            <i class="fa fa-chevron-left"></i>
            {{ membership.year }} - {{ membership.year|add:"1" }}
            <i class="fa fa-chevron-right"></i></h4>
        {% endifchanged %}

        <div class="col-md-2 col-sm-3">
            <div class="thumbnail mini-thumbnail">
                <img src="{{ membership.association.logo.url }}" alt="association logo">
                <div class="caption">
                    <a href="{% url 'associations.views.association_display' membership.association.name %}">
                      <h4>{{ membership.association.name }}</h4>
                    </a>
                </div>
            </div>
        </div>

    {% empty %}
        <p> Vous n'êtes dans aucune association.</p>
    {% endfor %}
    </div>

</div>
{% endblock %}

profiles/templates/profil.html
{% extends "base.html" %}

{% block title %}Eistiens.net :  profil de {{profile.pseudo}}{% endblock %}

{% block contenu %}

<div class="page-header">
<h2>{{user.first_name}} {{user.last_name}}<small>{{profile.get_status_display}}</small></h2>
</div>

<div id="div-profil-details" {% if "profil_edit" in active_forms %}style="display:none;"{% endif %} class="row">
	<div class="well span8">
		<p>{{profile.bio}}</p>

		<div style="margin-top:25px; margin-left:40px;">
			<h4>Informations personnelles et contact</h4>
			<p>
				<i class="icon-envelope"></i> e-mail : <a href="mailto:{{user.email}}">{{user.email}}</a><br>
				{% if profil.site_web %}<i class="icon-globe"></i> site personnel : <a href="#">derpy.brony.org</a><br>{% endif %}
				{% if profile.anniversaire %}<i class="icon-calendar"></i> anniversaire : {{profil.anniversaire}}<br>{% endif %}
			</p>
			<h4>Réseaux sociaux</h4>
			<p>
				{% if profile.linkedIN %}
					<i class="icon-briefcase"></i> profil linkedIn : <a href="{{profile.linkedIN}}">{{profile.linkedIN}}</a><br>{% endif %}
				{% if profile.viadeo %}
					<i class="icon-briefcase"></i> profil Viadeo : <a href="{{profile.viadeo}}">{{profile.viadeo}}</a><br>{% endif %}
				{% if profile.facebook %}
					<i class="icon-thumbs-up"></i> profil facebook : <a href="{{profile.facebook}}">{{profile.facebook}}</a><br>{% endif %}
				{% if profile.twitter %}
					<i class="icon-star"></i> profil twitter : <a href="{{profile.twitter}}">{{profile.twitter}}</a><br>{% endif %}
				{% if profile.google_plus %}
					<i class="icon-plus"></i> profil google+ : <a href="{{profile.google_plus}}">{{profile.google_plus}}</a><br>{% endif %}
			</p>
		</div>

	</div>
	<div class="span3">
		<img class="thumbnail" src="/media/{{ profile.avatar }}" alt="{{user}} profile avatar"/>

		{# Profile edition #}
		{% if user = request.user %}
		<a href="{% url 'profiles.views.edit_profile' user %}">
			<button id="btn-edit-profil" class="btn" type="button" style="margin-top:5px;">
				<i class="icon-pencil"></i>Éditer mon profil
			</button>
		</a>

    <a href="{% url 'profiles.views.inbox' %}">
        <button class="btn" type="button" style="margin-top:5px;">
            <span class="badge badge-important">{{ user.profile.get_nb_unread_messages }} <i class="icon-envelope icon-white"></i></span>	Messages
        </button>
    </a>
    {% endif %}
    </div>
</div>

<h3>Fabulousity : niveau 2</h3>

<div class="row">
	
	<img src="/media/tmp/trophy.png" class="offset1 span1">

	<div class="span6">
		<div class="progress progress-striped active progress-success" style="margin-top:20px;">
			<div class="bar" style="width: 70%;"></div>
		</div>
		<p><small>9001 points de Fabulousity</small></p>
    </div>

    

</div>

<h3>Mes associations</h3>

{% for m in memberships %}
	{% ifchanged m.annee %}
		{% if not forloop.first%}
	</ul>
		{% endif %}
	<h5>Année {{m.annee}}-{{m.annee|add:"1"}}</h5><ul>
	{% endifchanged %}
		<li>
			<a href="{% url 'associations.views.association_display' m.association.nom %}">{{m.association.nom}}</a> : {{m.get_statut_display}}
		</li>

	{% if forloop.last %}
	</ul>
	{% endif %}
{% empty %}
	<p> {{user}} n'est inscrit dans aucune association.</p>
{% endfor %}

{% endblock %}

profiles/templates/profile.html
{% extends "base2.html" %}


{% block template-specific-css %}
<!-- Assocation thumbnails CSS -->
<link href="/media/css/associations.css" rel="stylesheet">
{% endblock %}


{% block content-block %}
<div class="container">

    <!-- Event cover -->
    <div class="cover row-fluid user-cover" style="background-image:url('/media/img/users/cover_default.png');">
        <div class="col-md-3 col-sm-4 col-xs-5  user-portrait">
            <img src="{{ user.profile.avatar.url }}" class="img-circle">
            <h3>
                {{ user.first_name }} {{ user.last_name }}
                {% if request.user == user %}
                <span class="label label-default">c'est vous !</span>
                {% endif %}
            </h3>
            
            {% if user.profile.get_status_display %}
            <h4>{{ user.profile.get_status_display }}</h4>
            {% endif %}
        </div>

    </div><!-- /Event cover -->

    <div class="event-body">

        <!-- Event header -->
        <div class="row">
            <div class="col-md-8">
                {% if user.profile.bio %}
                <div class="row">
                    <div class="col-md-1 col-sm-2 col-xs-1">
                        <p><i class="fa fa-file-text fa-3x"></i></p>
                    </div>
                    <p class="col-md-11 col-sm-10 col-xs-11">
                        {{ user.profile.bio|linebreaksbr }}
                    </p>
                </div>
                {% endif %}
            </div>

            <div class="col-md-4">
                <p>
                    {% if request.user == user %}
                    <a class="btn btn-default btn-lg btn-block" href="{% url 'profiles.views.edit_profile' user.username %}">
                        <i class="fa fa-wrench"></i> Éditer mon profil
                    </a>
                    {% else %}
                    <a class="btn btn-default btn-lg btn-block" href="{% url 'messaging.views.privatethreads' %}?destinataire={{ user.username }}">
                        <i class="fa fa-envelope-o"></i> Envoyer un message
                    </a>
                    {% endif %}
                </p>
            </div>

        </div><!-- /Event header -->
        <hr>

        <h4>Contact</h4>
        <div class="row user-contact">

            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-envelope"></i> {{ user.email }}</p>
            </div>

            {% if user.profile.twitter %}
            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-twitter"></i> <a href="{{ user.profile.twitter }}"> profil Twitter</a></p>
            </div>
            {% endif %}

            {% if user.profile.facebook %}
            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-facebook"></i> <a href="{{ user.profile.facebook }}">profil Facebook</a></p>
            </div>
            {% endif %}

            {% if user.profile.google_plus %}
            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-google-plus"></i> <a href="{{ user.profile.google_plus }}">profil Google+</a></p>
            </div>
            {% endif %}

            {% if user.profile.linkedIN %}
            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-linkedin"></i> <a href="{{ user.profile.linkedIN }}">profil LinkedIN</a></p>
            </div>
            {% endif %}

            {% if user.profile.viadeo %}
            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-suitcase"></i> <a href="{{ user.profile.viadeo }}">profil Viadeo</a></p>
            </div>
            {% endif %}

            {% if user.profile.website %}
            <div class="col-md-4 col-sm-6 col-xs-6">
                <p><i class="fa fa-cog"></i> <a href="{{ user.profile.website }}">Site internet</a></p>
            </div>
            {% endif %}
        </div>
        <hr>

        <h4>Associations</h4>

        <div class="row">
        {% for membership in memberships %}

            {% ifchanged membership.year %}
            <h4 class="user-membership-year col-md-12 col-sm-12 col-xs-12">
                <i class="fa fa-chevron-left"></i>
                {{ membership.year }} - {{ membership.year|add:"1" }}
                <i class="fa fa-chevron-right"></i></h4>
            {% endifchanged %}


            <div class="col-md-2 col-sm-3">
                <div class="thumbnail mini-thumbnail">
                    <img src="{{ membership.association.logo.url }}" alt="association logo">
                    <div class="caption">
                        <a href="{% url 'associations.views.association_display' membership.association.name %}">
                          <h4>{{ membership.association.name }}</h4>
                        </a>
                    </div>
                </div>
            </div>

        {% endfor %}
        </div>
    </div>

</div>
{% endblock %}


{% block template-specific-js %}
<!-- BlurJS -->
<script src="/media/js/blur.min.js"></script>
<script>
$(document).ready( function() {
    $('.user-portrait').blurjs({ 
        source: '.user-cover',
        cache: true,
        radius: 15,
        overlay: 'rgba(91,91,91,0.1)'
    });
});
</script>
{% endblock %}

profiles/templates/profile_edition.html
{% extends "base2.html" %}
{% load widget_tweaks %}


{% block template-specific-css %}
<!-- Assocation thumbnails CSS -->
<link href="/media/css/associations.css" rel="stylesheet">
<link href="/media/css/datepicker3.css" rel="stylesheet">
{% endblock %}



{% block content-block %}


<div class="tooltip-area">
    <div class="container">
        <h1 class="text-center">Édition du profil</h1>
    </div> 
</div><!-- /Tooltip area -->

<div class="container container-on-top">


    {% if messages %}
    {% for message in messages %}
    {% if message.level = 40 %}
    <div class="callout callout-danger">
    {% elif message.level = 25 %}
    <div class="callout callout-info">
    {% else %}
    <div class="callout callout-warning">
    {% endif %}

    <h4>{{message}}</h4>

    {% if message.level = 40 %}
        <p>Vous devriez sans doute vérifier si les champs du formulaire sont correctement remplis.<p>
    {% elif message.level = 25 %}
        <p>
            <a class="btn btn-default" href="{% url 'profiles.views.display_profile' user.username %}">Retourner au profil</a>
        </p>
    {% endif %}
    </div>
    {% endfor %}
    {% endif %}

    <form enctype="multipart/form-data" action="" method="post">
        <fieldset>
            {% csrf_token %}

            {% for field in profile_edition_form %}
            <div class="form-group">
            <label for={{ field.auto_id }}>{{ field.label }}</label>
            {{ field|attr:"class:form-control" }}
            </div>
            {% endfor %}

            <div class="form-actions pull-right">
                <button type="submit" class="btn btn-primary">Sauvegarder</button>
                <a class="btn btn-default" href="{% url 'profiles.views.display_profile' user.username %}">Annuler</a>
            </div>
        </fieldset>
    </form>

</div>
{% endblock %}

{% block template-specific-js %}
<!-- Datepicker -->
<script src="/media/js/bootstrap-datepicker.js"></script>
<script src="/media/js/bootstrap-datepicker.fr.js" charset="UTF-8"></script>
<script>
$(document).ready( function() {

    $('#id_birthdate').datepicker({
        format: "dd/mm/yyyy",
        startView: 2,
        language: "fr",
        orientation: "bottom auto"
    });
});
</script>
{% endblock %}