api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^asso/(?P<association_name>\w+)/board_members.json$',
        'api.views.association_board_members_name'),
)

associations/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^$', 'associations.views.associations_home'),

    url(r'^(?P<association_name>[\w\W]+)/$',
        'associations.views.association_display'),

    url(r'^(?P<association_name>[\w\W]+)/register$',
        'associations.views.register_member'),

    url(r'^(?P<association_name>[\w\W]+)/conditions$',
        'associations.views.membership_conditions'),

    # Admin pages
    # Those views must be only usable by logged board members.

    url(r'^(?P<association_name>[\w\W]+)/admin/infos$',
        'associations.views.admin_general_infos'),

    url(r'^(?P<association_name>[\w\W]+)/admin/activites$',
        'associations.views.admin_activities'),

    url(r'^(?P<association_name>[\w\W]+)/admin/activites/'
        '(?P<activity_id>\w+)/edit$',
        'associations.views.admin_activity_edit'),

    url(r'^(?P<association_name>[\w\W]+)/admin/activites/'
        '(?P<activity_id>\w+)/delete$',
        'associations.views.admin_activity_delete'),

    url(r'^(?P<association_name>[\w\W]+)/admin/evenements$',
        'associations.views.admin_events'),

    url(r'^(?P<association_name>[\w\W]+)/admin/evenements/'
        '(?P<event_id>\w+)/edit$',
        'associations.views.admin_events_edit'),

    url(r'^(?P<association_name>[\w\W]+)/admin/evenements/'
        '(?P<event_id>\w+)/paye/(?P<member_id>\w+)$',
        'associations.views.admin_events_set_paid'),

    url(r'^(?P<association_name>[\w\W]+)/admin/bureau$',
        'associations.views.admin_board'),

    url(r'^(?P<association_name>[\w\W]+)/admin/bureau/'
        '(?P<member_id>\w+)/ajouter/(?P<role>[\w\W]+)$',
        'associations.views.admin_board_add_member'),

    url(r'^(?P<association_name>[\w\W]+)/admin/bureau/'
        '(?P<member_id>\w+)/kick$',
        'associations.views.admin_board_kick_member'),

    url(r'^(?P<association_name>[\w\W]+)/admin/membres$',
        'associations.views.admin_members'),

    url(r'^(?P<association_name>[\w\W]+)/admin/membres/'
        'message/(?P<recipients>\w+)$',
        'associations.views.admin_send_message'),

    url(r'^(?P<association_name>[\w\W]+)/admin/membres/'
        '(?P<member_id>\w+)/kick$',
        'associations.views.admin_members_kick_member'),

    url(r'^(?P<association_name>[\w\W]+)/admin/membres/'
        '(?P<member_id>\w+)/cotisation$',
        'associations.views.admin_members_set_subscription'),

    url(r'^(?P<association_name>[\w\W]+)/admin/passation$',
        'associations.views.admin_signing'),

    url(r'^(?P<association_name>[\w\W]+)/admin/help$',
        'associations.views.admin_help'),
)

eistiens_net/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns(
    '',

    # Associations app
    url(r'^associations/', include('associations.urls')),

    # Events app
    url(r'^evenements/', include('events.urls')),

    # Profiles app
    url(r'^profils/', include('profiles.urls')),

    # Messages
    url(r'^messages/', include('messaging.urls')),

    # Schedules
    url(r'^edt/', include('schedule.urls')),

    # API
    url(r'^api/', include('api.urls')),

    # local
    url(r'^locaux/', include('rooms.urls')),

    # Jobs
    url(r'^jobs/', include('jobs.urls')),

    # Facts
    url(r'^facts/', include('facts.urls')),

    # Portal app
    url(r'^', include('portal.urls')),

    # Medias
    # ! FOR TEST SERVER ONLY !
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # Grapelli urls : admin panel template
    url(r'^grappelli/', include('grappelli.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

associations/models.py
# coding: utf-8

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models

import markdown2

from rooms.models import Room
from eistiens_net import util

from jobs.api import sanitize


def not_negative(value):
    if value < 0:
        raise ValidationError(u'The value has to be positive.')


class Association(models.Model):
    """
    An association instance reprensent a real-life student organisation.

    It has several attributes like the cotisation fee, a short description, in
    which campus it is located, etc.
    """

    name = models.CharField("Nom de l'association", max_length=64)

    description = models.TextField(
        "Description brève du rôle de l'association", blank=True)

    markdown_description = models.TextField(
            "Description brève du rôle de l'association (markdown)")

    website = models.URLField(
        "Site web de l'association",
        blank=True, null=True)

    logo = models.ImageField(
        "Logo de l'association",
        upload_to='img/associations/logos/',
        default='img/associations/logo_default.png')

    cover_image = models.ImageField(
        "Cover image",
        upload_to='img/associations/covers/',
        default='img/associations/cover_default.png')

    cover_caption = models.CharField(
        "Cover caption",
        max_length=512, blank=True, null=True)

    CAMPUS = (
        (0, "Cergy"),
        (1, "Pau"),
    )
    campus = models.SmallIntegerField("Campus", choices=CAMPUS)

    room = models.ForeignKey(
        Room,
        verbose_name='Local', blank=True, null=True)

    subscription = models.PositiveIntegerField(
        "Coût de la cotisation (laisser zéro si aucune)",
        default=0)

    signing_year = models.PositiveIntegerField('Année du bureau actuel', default=util.get_current_year())

    members = models.ManyToManyField(User, through='Member')

    def get_activities(self):
        """
        Returns a query set with all the association's activities.
        """
        return Activity.objects.filter(association=self.id)

    def get_board_members(self):
        """
        Returns a query set containing all the current board members, ordered
        by rank (most important first).
        """

        return Member.objects.filter(
            association=self.id,
            year=self.signing_year,
            status__lt=5).order_by('status')

    def get_members(self):
        """
        Returns a query set containing all the current year's members that are
        not in the board.
        """

        # TODO add options to optionaly order this set (by activity, or name
        # for instance).
        if self.signing_year == util.get_current_year():
            return Member.objects.filter(
                association=self.id, year=util.get_current_year(), status__gt=4)

        return Member.objects.filter(
                association=self.id, year=util.get_current_year())

    def get_all_members(self):
        """
        Returns a list containing all the current year's members.
        """

        return Member.objects.filter(
            association=self.id,
            year=util.get_current_year()).order_by(
                'status', 'user__last_name', 'user__first_name')

    def get_all_members_id(self):
        """
        Returns a list containing the IDs of all the current year's members,
        board members and simple members alike.
        """

        return Member.objects.filter(
            association=self.id,
            year=util.get_current_year()).values_list('user', flat=True)

    def get_president(self):
        """
        Returns the member designated as the president of the association
        """

        return Member.objects.get(
            association=self.id,
            year=self.signing_year,
            status=0)

    def is_passation_done(self):
        return Member.objects.filter(
            association=self.id,
            year=util.get_current_year()+1, status=0).exists()

    def save(self, *args, **kwargs):
        self.description = markdown2.markdown(self.markdown_description)
        self.description = sanitize(self.description)
        super(Association, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class GalleryImage(models.Model):
    """
    Galleries are an integrated picture and photos hosting system.

    It could be a convenient place to store events photos or posters.
    """

    # TODO : this model class is not used anywhere yet
    association = models.ForeignKey(Association)

    image = models.ImageField(
        "Photo ou image", upload_to='associations/logos/')


class Activity(models.Model):
    """
    Activities are the "features" of the association : what members usually do,
    and so on.

    Activities are not to be mixed up with events. Events are punctual whereas
    actities are more on a regular basis. For instance, if the sports
    association organizes a training session each week, it is more an activity
    than an event.
    """

    association = models.ForeignKey(Association)

    title = models.CharField("Titre de l'activité", max_length=150)

    description = models.TextField("Description courte", blank=True)

    markdown_description = models.TextField("Description courte (markdown)")

    image = models.ImageField(
        "Image de miniature",
        upload_to='associations/activites/')

    recurrence = models.CharField(
        "Récurrence de l'évènement",
        max_length=150, blank=True, null=True)

    website = models.URLField("Site web de l'activité", blank=True, null=True)

    def save(self, *args, **kwargs):
        self.description = markdown2.markdown(self.markdown_description)
        self.description = sanitize(self.description)
        super(Activity, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.association.__unicode__() + " : " + self.title


class Achievement(models.Model):
    """
    Distinctions are badges awarded to active members.
    """

    # TODO : this model class is not used anywhere yet
    association = models.ForeignKey(Association)

    title = models.CharField("Titre de la distinction", max_length=50)

    description = models.TextField("Description de la distinction")

    image = models.ImageField(
        "Icône de la distinction",
        upload_to='associations/distinctions', blank=True, null=True)

    def __unicode__(self):
        return self.association + " : " + self.title


class Member(models.Model):
    """
    A member is a user that is taking part to an association's actities.

    Members may have different statuses. Some are board members and thus can
    access the administration panel for the assiciation. Each membership
    contains the year, so the system can keep track of former members.
    """

    user = models.ForeignKey(User, verbose_name="Identité du membre")

    association = models.ForeignKey(Association, verbose_name="Association")

    MEMBER_STATUS = (
        (0, "Président"),
        (1, "Vice Président"),
        (2, "Secrétaire"),
        (3, "Trésorier"),
        (4, "Membre du bureau"),
        # Status 5 to 9 are available for future use
        (10, "Membre")
    )
    status = models.SmallIntegerField(
        "Statut du Membre",
        choices=MEMBER_STATUS)

    year = models.IntegerField("Année du début de l'inscritpion")

    subscription_paid = models.BooleanField("cotisation payée", default=False)

    achievements = models.ManyToManyField(Achievement, blank=True, null=True)

    def get_basic_member_status(self):
        for k, status in Member.MEMBER_STATUS:
            if status == "Membre":
                return k

    def __unicode__(self):
        return str(self.user) + "  (" + self.get_status_display() + \
            " " + self.association.name + ")"

jobs/models.py
# coding: utf-8

import markdown2

from django.contrib.auth.models import User
from django.db import models

from jobs.api import sanitize


class Enterprise(models.Model):
    """
    An enterprise is made up of a name, a logo and a location,
    users can add reviews, interview questions and contacts they have
    within a given enterprise.
    """

    name = models.CharField('Nom de l\'entreprise', max_length=256)

    logo = models.ImageField(
        'Logo de l\'entreprise',
        upload_to='img/enterprises/logos/',
        default='img/enterprises/default_logo_128.png')

    website = models.URLField('Site internet', blank=True, null=True)

    location = models.CharField(
        'Lieu de l\'entreprise (Ville, Pays)', max_length=256)

    markdown_description = models.TextField(
        'Brève description de ce que fait l\'entreprise (markdown)')

    description = models.TextField(
        'Brève description de ce que fait l\'entreprise', blank=True)

    users = models.ManyToManyField(User)

    def save(self, *args, **kwargs):
        self.description = markdown2.markdown(self.markdown_description)
        self.description = sanitize(self.description)
        super(Enterprise, self).save(*args, **kwargs)

    def __unicode__(self):
        return unicode(self.name) + ' - ' + self.location


class Contact(models.Model):
    """
    A contact in an enterprise, represented as a name, a role in the
    enterprise and telephone number + mail.
    """

    enterprise = models.ForeignKey(Enterprise, verbose_name='Entreprise')

    user = models.ForeignKey(User, verbose_name='Eistien')

    name = models.CharField('Nom du contact', max_length=256)

    role = models.CharField('Poste dans l\'entreprise', max_length=256)

    mail = models.CharField('Adresse e-mail', max_length=256)

    phone = models.CharField('Numéro de téléphone', max_length=256)

    def __unicode__(self):
        return unicode(self.name) + ' - ' + unicode(self.enterprise)


class Question(models.Model):
    """
    A question asked during an interview, represented as a text and the role the user
    was applying for.
    """

    enterprise = models.ForeignKey(Enterprise, verbose_name='Entreprise')

    user = models.ForeignKey(User, verbose_name='Eistien')

    markdown_text = models.TextField('Question (markdown)')

    text = models.TextField('Question', blank=True)

    requested_role = models.CharField(
        'Candidature pour un poste de', max_length=256)

    publication_date = models.DateTimeField(
        'Date de publication', auto_now_add=True)

    def save(self, *args, **kwargs):
        self.text = markdown2.markdown(self.markdown_text)
        self.text = sanitize(self.text)
        super(Question, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'Question posée à ' + unicode(self.user)


class Review(models.Model):
    """
    The review of an enterprise, a review text, the wage of the user,
    the year of the user when he/she did the internship (ING1, ING2, ING3)
    """

    enterprise = models.ForeignKey(Enterprise, verbose_name='Entreprise')

    user = models.ForeignKey(User, verbose_name='Eistien')

    markdown_review = models.TextField('Critique (positive ou négative) du stage (markdown)')

    review = models.TextField('Critique (positive ou négative) du stage', blank=True)

    wage = models.CharField('Salaire', max_length=256)

    YEARS = (
        (0, 'CPI'),
        (1, 'ING1'),
        (2, 'ING2'),
        (3, 'ING3'),
        (4, 'Autre'),
    )
    year = models.SmallIntegerField('Année d\'étude', choices=YEARS)

    publication_date = models.DateTimeField(
        'Date de publication', auto_now_add=True)

    def save(self, *args, **kwargs):
        self.review = markdown2.markdown(self.markdown_review)
        self.review = sanitize(self.review)
        super(Review, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'Critique par ' + unicode(self.user)

associations/forms.py
# coding: utf-8

from django import forms

from associations.models import Association, Member, Activity


class GeneralInformationForm(forms.ModelForm):
    """
    ModelForm to edit an association's parameters and informations.
    """

    class Meta:
        model = Association
        fields = ['markdown_description', 'website', 'logo', 'cover_image', 'subscription']


class ActivityForm(forms.ModelForm):
    """
    ModelForm to create or edit an association's activity.
    """

    class Meta:
        model = Activity
        exclude = ['association', 'description']


class NewBoardMemberForm(forms.Form):
    """
    Form used to add a new member to the board.
    """

    name = forms.CharField()
    status = forms.ChoiceField(Member.MEMBER_STATUS[:4])


class ConditionsAgreementForm(forms.Form):
    """
    Agreement form for new association members.
    """

    agreement = forms.CharField()

associations/templates/admin_events_edit.html
{% extends "association_admin.html" %}

{% load portal_extras %}

{% block admin_menu %}
	{% include "admin_menu.html" with active_tab='tab3' asso_name=association.name %}
{% endblock %}

{% block template-specific-css %}
<link href="/media/css/datepicker3.css" rel="stylesheet">
{% endblock %}

{% block form %}
<h3>{{event.titre}}</h3>

{% if not event.authorized %}
<div class="alert alert-error">
	<h4 class="alert-heading">Cet événement n'a pas encore été validé par un membre de l'administration.</h4>
	<p>Le processus de validation a pour objectif de permettre à l'administration d'avoir un regard sur l'activité associative ainsi que de s'assurer de la disponibilité des salles.</p>

	<p><a class="btn" data-toggle="modal" data-target="#validation-process-modal">En savoir plus sur la validation</a> <a class="btn btn-danger" href="{% url 'messaging.views.privatethreads' %}?destinataire=administration">Demander un recours</a></p>
</div>
{% else %}
<div class="alert alert-success">
	L'évènement a été validé !
</div>
{% endif %}


<ul class="nav nav-tabs">
	<li{% if not tab or tab == "infos" %} class="active"{% endif %}><a href="#infos" data-toggle="tab">Informations</a></li>
	<li{% if tab == "participants" %} class="active"{% endif %}><a href="#participants" data-toggle="tab">Participants</a></li>
</ul>

{% if not event.is_past_event %}
<div id="edit-event-div" style="display: none">
	<div class="modal-header">
		<button type="button" class="close btn-edit-event-cancel" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 id="myModalLabel">Éditer évènement</h3>
	</div>
	<form id="edit-event-form" enctype="multipart/form-data" action="{% url 'associations.views.admin_events_edit' association.name event.id %}" method="post">
		<div class="modal-body">
			<fieldset>
				{% csrf_token %}
				{{ form.as_p|bootstrap|safe }}
			</fieldset>
		</div>
		<div class="modal-footer">
                <input type="hidden" name="action" value="edit_event"/>
				<button class="btn btn-cancel btn-edit-event-cancel" onclick="$('#edit-event-div').hide();$('.btn-edit-event').show();">Annuler</button>
				<button type="submit" class="btn btn-primary">Éditer</button>
		</div>
	</form>
</div>
{% endif %}

<div id="details-event-div" class="tab-content">
	<div class="tab-pane {% if not tab or tab == "infos" %} active{% endif %}" id="infos">
		<div class="row">
			<div class="span6">
				<h4>Informations sur l'évènement
					{% if not event.is_past_event %}
					<a id="btn-edit-event" href="#" onclick="$('#edit-event-div').show();$('#btn-edit-event').hide();">
						<button class="btn btn-small btn-edit-event" type="button"><i href="{% url 'associations.views.admin_events_edit' association.name event.id %}" class="icon-pencil" oncli></i> Éditer</button>
					</a>
					{% endif %}
				</h4>
				<div style="padding-left:20px;">
				<p>
					<i class="icon-calendar"></i> {{ event.day|date:"l j F" }}<br>
					<i class="icon-time"></i> de {{ event.start_time }} à {{ event.end_time }}<br>
					<i class="icon-globe"></i> {{ event.get_location_display }} {% if event.location < 3 %}{{ event.room }}
					{% else %}<br><i class="icon-road"></i> Adresse : {{ event.address }}{% endif %}
				</p>
				<h5>Description :</h5>
				<p>{{event.description}}</p>
				</div>

			</div>
			<p class="well pull-right">
				{% if event.registration_cost != 0 %}<span class="label label-danger">Payant</span><br>{% endif %}
				{% if event.registered_only %}<span class="label label-warning">Inscription obligatoire</span><br>{% endif %}
				{% if event.registration_cost == 0 and not event.registered_only %}<span class="label label-success">Entrée libre</span><br>{% endif %}				
			</p>
		</div>

		<div>
			<h4>Taux d'inscription</h4>
			<p>{% if event.registered_only %}<span class="badge">{{ event.max_nb_participants }}</span> places prévues,{% endif %}
			<span class="badge alert-info">{{ participants.count }}</span> personnes inscrites<br>
			{% if event.registration_cost != 0 %}<span class="badge alert-success">{{ paid.count }}</span> inscriptions payées,
			<span class="badge alert-danger">{{ unpaid.count }}</span> en attente de paiement{% endif %}</p>
		    <div class="progress">
				<div class="progress-bar progress-bar-success" style="width:{% widthratio paid.count event.max_nb_participants 100 %}%;"></div>
				<div class="progress-bar progress-bar-danger" style="width:{% widthratio unpaid.count event.max_nb_participants 100 %}%;"></div>
			</div>
		</div>
	</div>

	<div class="tab-pane {% if tab == "participants" %} active{% endif %}" id="participants">
		<br>
		{% if participants %}
		<button class="btn"><i class="icon-envelope"></i> Message à tous les participants</button>
		<button class="btn btn-danger"> Message aux impayés</button>
		<br>

		<table class="table table-hover">
		<thead>
			<tr><th>Nom</th><th>Prénom</th>{% if event.registration_cost != 0 %}<th>Frais d'inscription</th>{% endif %}<th>Inscrit le</th><th></th></tr>
		</thead>
		<tbody>
			{% for i in participants %}
			<tr>
				<td>{{ i.user.last_name}}</td>
				<td>{{ i.user.first_name}}</td>
				{% if event.registration_cost != 0 %}
				<td>
					<a href="{% url 'associations.views.admin_events_set_paid' association.name event.id i.user.id %}">
						{% if i.paid %}<span class="badge alert-success">oui</span>
						{% else %}<span class="badge alert-danger">non</span>{% endif %}
					</a>
				</td>
				{% endif %}
				<td>{{ i.registration_date }}</td>
				<td><a href="{% url 'profiles.views.display_profile' i.user.username %}">Voir le profil</a></td>
			</tr>
			{% endfor %}
		</tbody>
		</table>
		{% else %}
		<p>Il n'y a pas encore de participant à cet événement.</p>
		{% endif %}
	</div>
</div>

<div class="modal fade" id="validation-process-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
				<h3 id="myModalLabel">Processus de validation</h3>
			</div>
			<div class="modal-body">
				Lorsque vous décidez d'organiser un événement et que vous publiez celui-ci sur le site,
				il apparait dans la liste des événements en attente de validation.
				<br><br>
				Cette liste n'est accessible qu'à l'administration de <b>L'EISTI</b>, et ils sont donc les
				seuls à avoir le pouvoir de validation des différents événements organisés au sein de l'école.
				<br><br>
				Vous devez donc attendre la validation de leur part, ou demander un recours pour leur envoyer
				un message leur demandant des explications sur la non-validation de l'événement.
			</div>
			<div class="modal-footer">
				<button class="btn" data-dismiss="modal" aria-hidden="true">Fermer</button>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block template-specific-js %}
<!-- Datepicker -->
<script src="/media/js/bootstrap-datepicker.js"></script>
<script src="/media/js/bootstrap-datepicker.fr.js" charset="UTF-8"></script>
<script>
$(document).ready( function() {

    $('#id_day').datepicker({
        format: "dd/mm/yyyy",
        language: "fr",
        orientation: "bottom auto"
    });
});
</script>
{% endblock %}

associations/templates/association.html
{% extends "portail_assos.html" %}

{% block title %}Eistiens.net :  Association {{asso.nom}}{% endblock %}

{% block contenu %}

{% if member %}
<div class="hero-unit" style="background-image:url({{asso.get_logo_url}}); background-repeat:no-repeat; background-position:right;">

	<h2>Association {{asso.nom}}</h2>
	<p>
		{{asso.description}} - campus de {{asso.get_campus_display}}
	</p>

	{% if member.statut < 5 %}
	<div class="btn-group btn-group-vertical">
		<a class="btn btn-success btn-large" href="#">Vous êtes {{member.get_statut_display}} !</a>
		<a class="btn" href="{% url 'associations.views.admin_general_infos' asso.nom %}">
			<i class="icon-wrench"></i> Panneau d'administration &raquo;
		</a>
	</div>
	{% else %}
	<p><a class="btn btn-success btn-large" href="#">Vous êtes {{member.get_statut_display}} !</a></p>
	{% endif %}
	
</div>
{% else %}
<div class="hero-unit" style="background-image:url({{asso.get_logo_url}}); background-repeat:no-repeat; background-position:right;">
	<h2>Association {{asso.nom}}</h2>
	<p>
		{{asso.description}} - campus de {{asso.get_campus_display}}
	</p>
	<p><a href="{% url 'associations.views.register_member' asso.nom %}" class="btn btn-warning btn-large">Devenir membre &raquo;</a></p>
</div>
{% endif %}

{% if not member.cotisation_payee and asso.cotisation > 0 %}
<div class="alert alert-error">
<i class="icon-warning-sign"> </i>
<strong>Attention !</strong> Il semblerait que vous n'ayez pas payé votre <strong>cotisation</strong> à cette association (d'un montant de <strong>{{asso.cotisation}}€</strong>).
Pensez à contacter le bureau pour régler ça !
</div>
{% endif %}

<h3>Évènements et activités</h3>

{% for a in activites %}
{% if forloop.counter0|divisibleby:"4" %}
<ul class="thumbnails">
{% endif %}
	<li class="span3">
		<div class="thumbnail">
			<img src="{{a.miniature.url}}" alt="">
			<div class="caption">
				<h4>{{a.titre}}</h4>
				<p>{{a.description_courte}}</p>
				<p>
					{% if a.recurrence %}<p><i class="icon-time"></i> <strong>{{a.recurrence}}</strong></p>{% endif %}
					{% if a.url %}<a href="{{a.url}}" class="btn btn-info"><i class="icon-globe icon-white"></i> Site web</a>{% endif %}
				</p>
			</div>
		</div>
	</li>

{% if forloop.counter|divisibleby:"4" %}
</ul>
{% endif %}
{% endfor %}
</ul>

{% for eve in evenements %}
<div class="well well-small" style="padding-bottom:0px;">
	<ul class="thumbnails" style="margin-bottom:-10px;">
		<li class="span1"><img src="/media/tmp/3.png" class="img-circle" style="height:70px;"></li>
		<li class="span5">
			<strong>{{eve.jour|date:"l j F"}} : {{eve.titre}}</strong>
			<p>{{eve.description}}</p>
			<p style="margin-bottom:0px;">
				<i class="icon-flag"></i> Organisé par : <strong>
				<a href="{% url 'associations.views.association_display' eve.organizer.nom %}">{{eve.organizer}}</a></strong><br/>
				<i class="icon-time"></i> Heure : <strong>de {{eve.debut}} à {{eve.fin}}</strong>
			</p>
		</li>
		
		<li class="span1">
			{% if eve.payant %}<span class="label label-important">Payant</span><br>{% endif %}
			{% if eve.inscription_necessaire %}<span class="label label-warning">Inscription obligatoire</span>{% endif %}
			{% if not eve.payant and not eve.inscription_necessaire %}<span class="label label-success">Entrée libre</span>{% endif %}
		</li>
		
		<li class="span3 pull-right">
			<a href="{% url 'events.views.display_event' eve.id %}">
				<button class="btn btn-large btn-primary" type="button" style="margin-top:10px;">Informations et inscription</button>
			</a>
		</li>
	</ul>
</div>
{% endfor %}

<h3>Membre du bureau de {{asso.nom}}</h3>

<div class="row" style="margin-top:30px;">

{% for m in membres %}
{% if m.statut < 5 %}
	<div class="span2">
		<img src="{{m.identite.profile.avatar.url}}" class="img-circle img-polaroid" style="margin-left: 80px; height:100px; width:100px;">
	</div>
	<div class="span2">
		<h4>{{m.identite.first_name}} {{m.identite.last_name}}</h4>
		<p>{{m.get_statut_display}}<br/><a class="btn" href="{% url 'profiles.views.display_profile' m.identite.username %}">Contacter &raquo;</a></p>
	</div>
{% endif %}
{% endfor %}
</div>

<h3>Liste des membres</h3>

<table class="table table-hover">
<thead><tr><th>Nom</th><th>Prénom</th><th>Rôle</th><th>Statut</th></tr></thead>
<tbody>
{% for m in membres %}
<tr>
  <td>{{m.identite.last_name}}</td>
  <td>{{m.identite.first_name}}</td>
  <td>{{m.get_statut_display}}</td>
  <td>{{m.identite.profile.get_statut_display}}</td>
</tr>
{% empty %}
Il n'y a pas encore de membres par ici !
{% endfor %}
</tbody>
</table>


{% endblock %}