api/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^asso/(?P<association_name>\w+)/board_members.json$',
        'api.views.association_board_members_name'),
)

eistiens_net/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings


admin.autodiscover()

urlpatterns = patterns(
    '',

    # Associations app
    url(r'^associations/', include('associations.urls')),

    # Events app
    url(r'^evenements/', include('events.urls')),

    # Profiles app
    url(r'^profils/', include('profiles.urls')),

    # Messages
    url(r'^messages/', include('messaging.urls')),

    # Schedules
    url(r'^edt/', include('schedule.urls')),

    # API
    url(r'^api/', include('api.urls')),

    # local
    url(r'^locaux/', include('rooms.urls')),

    # Jobs
    url(r'^jobs/', include('jobs.urls')),

    # Facts
    url(r'^facts/', include('facts.urls')),

    # Portal app
    url(r'^', include('portal.urls')),

    # Medias
    # ! FOR TEST SERVER ONLY !
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),

    # Grapelli urls : admin panel template
    url(r'^grappelli/', include('grappelli.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

jobs/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',

    url(r'^$', 'jobs.views.jobs'),
    url(r'^ajouter$', 'jobs.views.add_entry'),
    url(r'^entreprise/editer/(?P<enterprise_id>\w+)$', 'jobs.views.update_enterprise'),
    url(r'^entreprise/(?P<enterprise_id>\w+)$', 'jobs.views.enterprise'),
    url(r'^supprimer_critique/(?P<review_id>\w+)$', 'jobs.views.delete_review'),
    url(r'^supprimer_question/(?P<question_id>\w+)$', 'jobs.views.delete_question'),
)

jobs/models.py
# coding: utf-8

import markdown2

from django.contrib.auth.models import User
from django.db import models

from jobs.api import sanitize


class Enterprise(models.Model):
    """
    An enterprise is made up of a name, a logo and a location,
    users can add reviews, interview questions and contacts they have
    within a given enterprise.
    """

    name = models.CharField('Nom de l\'entreprise', max_length=256)

    logo = models.ImageField(
        'Logo de l\'entreprise',
        upload_to='img/enterprises/logos/',
        default='img/enterprises/default_logo_128.png')

    website = models.URLField('Site internet', blank=True, null=True)

    location = models.CharField(
        'Lieu de l\'entreprise (Ville, Pays)', max_length=256)

    markdown_description = models.TextField(
        'Brève description de ce que fait l\'entreprise (markdown)')

    description = models.TextField(
        'Brève description de ce que fait l\'entreprise', blank=True)

    users = models.ManyToManyField(User)

    def save(self, *args, **kwargs):
        self.description = markdown2.markdown(self.markdown_description)
        self.description = sanitize(self.description)
        super(Enterprise, self).save(*args, **kwargs)

    def __unicode__(self):
        return unicode(self.name) + ' - ' + self.location


class Contact(models.Model):
    """
    A contact in an enterprise, represented as a name, a role in the
    enterprise and telephone number + mail.
    """

    enterprise = models.ForeignKey(Enterprise, verbose_name='Entreprise')

    user = models.ForeignKey(User, verbose_name='Eistien')

    name = models.CharField('Nom du contact', max_length=256)

    role = models.CharField('Poste dans l\'entreprise', max_length=256)

    mail = models.CharField('Adresse e-mail', max_length=256)

    phone = models.CharField('Numéro de téléphone', max_length=256)

    def __unicode__(self):
        return unicode(self.name) + ' - ' + unicode(self.enterprise)


class Question(models.Model):
    """
    A question asked during an interview, represented as a text and the role the user
    was applying for.
    """

    enterprise = models.ForeignKey(Enterprise, verbose_name='Entreprise')

    user = models.ForeignKey(User, verbose_name='Eistien')

    markdown_text = models.TextField('Question (markdown)')

    text = models.TextField('Question', blank=True)

    requested_role = models.CharField(
        'Candidature pour un poste de', max_length=256)

    publication_date = models.DateTimeField(
        'Date de publication', auto_now_add=True)

    def save(self, *args, **kwargs):
        self.text = markdown2.markdown(self.markdown_text)
        self.text = sanitize(self.text)
        super(Question, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'Question posée à ' + unicode(self.user)


class Review(models.Model):
    """
    The review of an enterprise, a review text, the wage of the user,
    the year of the user when he/she did the internship (ING1, ING2, ING3)
    """

    enterprise = models.ForeignKey(Enterprise, verbose_name='Entreprise')

    user = models.ForeignKey(User, verbose_name='Eistien')

    markdown_review = models.TextField('Critique (positive ou négative) du stage (markdown)')

    review = models.TextField('Critique (positive ou négative) du stage', blank=True)

    wage = models.CharField('Salaire', max_length=256)

    YEARS = (
        (0, 'CPI'),
        (1, 'ING1'),
        (2, 'ING2'),
        (3, 'ING3'),
        (4, 'Autre'),
    )
    year = models.SmallIntegerField('Année d\'étude', choices=YEARS)

    publication_date = models.DateTimeField(
        'Date de publication', auto_now_add=True)

    def save(self, *args, **kwargs):
        self.review = markdown2.markdown(self.markdown_review)
        self.review = sanitize(self.review)
        super(Review, self).save(*args, **kwargs)

    def __unicode__(self):
        return u'Critique par ' + unicode(self.user)

jobs/views.py
#coding: utf-8

from django.shortcuts import render_to_response, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
import tooltip

from jobs.models import Contact, Enterprise, Question, Review

import json


@login_required
def jobs(request):
    """
    Display a page where a user can see enterprises and their
    reviews/contacts/questions and create a new entry

    :param request: request object
    """

    enterprises = Enterprise.objects.all().order_by('name')

    tooltip.content(request,
        title="""Découvrez la base de données des entreprises !""",
        text="""Vous avez un stage à faire, ou voulez simplement vous informer
            sur les pratiques de certaines entreprises ? Sur cette page vous
            pouvez accéder à diverses informations sur les entreprises dans
            lesquelles des eistiens ont déjà candidaté: leurs critiques ainsi
            que les questions qui leur ont été posées lors de leur
            entretien.""")
    tooltip.icon(request, 'building-o')

    return render_to_response(
        'entreprises.html',
        {
            'request': request,
            'enterprises': enterprises
        }, context_instance=RequestContext(request))


@login_required
def add_entry(request):
    """
    Displays forms to let the user add an entry to the Jobs DB

    :param request: request objects
    """

    error = False

    if request.method == 'POST':
        other = ['other_name', 'other_location', 'other_description',
            'other_website']

        other_data = [request.POST.get(x, '') for x in other]

        if any(len(x) for x in other_data):
            if any(not len(x) for x in other_data):
                messages.error(request, u'Vous devez remplir tous les champs')
                error = True
            else:
                kwargs = {
                    'name': other_data[0],
                    'website': other_data[3],
                    'location': other_data[1],
                    'markdown_description': other_data[2]
                }

                if 'other_logo' in request.FILES:
                    kwargs['logo'] = request.FILES['other_logo']

                enterprise = Enterprise(**kwargs)
                enterprise.save()
                enterprise.users.add(request.user)
        else:
            try:
                enterprise = Enterprise.objects.get(
                    id=int(request.POST['enterprise']))
            except:
                messages.error(request, u'L\'entreprise n\'existe pas')
                error = True

        if not error:
            return HttpResponseRedirect(reverse_lazy(
                'jobs.views.update_enterprise',
                args=(enterprise.id,)))


    enterprises = Enterprise.objects.all().order_by('name')

    return render_to_response(
        'ajouter.html', {
            'request': request,
            'enterprises': enterprises
        }, context_instance=RequestContext(request))


@login_required
def update_enterprise(request, enterprise_id):
    """
    Allows a user to add reviews and interview questions for an enterprise.

    :param request: request object
    :param enterprise_id: id of the enterprise
    """

    enterprise = get_object_or_404(Enterprise, id=enterprise_id)

    if request.method == 'POST':
        success = True
        post_type = request.POST.get('type', '')

        if post_type == 'review':
            required = ['review', 'wage', 'year']
            required_data = [request.POST.get(x, '') for x in required]

            if any(not len(x) for x in required_data) or not required_data[2].isdigit():
                success = False
            else:
                review = Review(
                    enterprise=enterprise,
                    user=request.user,
                    markdown_review=required_data[0],
                    wage=required_data[1],
                    year=int(required_data[2]))
                review.save()

        elif post_type == 'question':
            required = ['question', 'role']
            required_data = [request.POST.get(x, '') for x in required]

            if any(not len(x) for x in required_data):
                success = False
            else:
                question = Question(
                    enterprise=enterprise,
                    user=request.user,
                    markdown_text=required_data[0],
                    requested_role=required_data[1])
                question.save()

        else:
            success = False

        if success and request.user not in enterprise.users.all():
            enterprise.users.add(request.user)

        return HttpResponse(json.dumps(
            {
                'success': success
            }), content_type='application/json')

    return render_to_response(
        'editer.html', {
            'request': request,
            'enterprise': enterprise,
            'years': Review.YEARS
        }, context_instance=RequestContext(request))


@login_required
def enterprise(request, enterprise_id):
    """
    Displays informations on an enterprise, contacts, interview questions
    and reviews.

    :param request: request object
    :param enterprise_id: id of the enterprise
    """

    enterprise = get_object_or_404(Enterprise, id=enterprise_id)
    
    reviews = Review.objects.filter(
        enterprise=enterprise_id).order_by('-publication_date')

    questions = Question.objects.filter(
        enterprise=enterprise_id).order_by('-publication_date')

    contacts = Contact.objects.filter(enterprise=enterprise_id)

    if request.method == 'POST':
        data_type, data_id = None, None

        if 'id' not in request.POST:
            messages.error(request, u'Formulaire invalide')
        else:
            form_id = request.POST['id'].split()
            if len(form_id) != 2 or not form_id[1].isdigit():
                messages.error(request, u'Formulaire invalide')
            else:
                data_type, data_id = form_id[0], int(form_id[1], 10)

        # The user wants to edit a review
        if data_type == 'review' and Review.objects.filter(id=data_id).exists():
            required = ['review', 'wage', 'year']
            required_data = [request.POST.get(x, '') for x in required]

            if any(not len(x) for x in required_data):
                messages.error(request, u'Un des champs est vide')
            else:
                review = Review.objects.get(id=data_id)

                if review.user != request.user:
                    messages.error(request, u'Formulaire invalide')
                else:
                    review.markdown_review = required_data[0]
                    review.wage = required_data[1]
                    review.year = int(required_data[2], 10)
                    review.save()

        # The user wants to edit a question
        elif data_type == 'question' and Question.objects.filter(id=data_id).exists():
            required = ['question', 'role']
            required_data = [request.POST.get(x, '') for x in required]

            if any(not len(x) for x in required_data):
                messages.error(request, u'Un des champs est vide')
            else:
                question = Question.objects.get(id=data_id)

                if question.user != request.user:
                    messages.error(request, u'Formulaire invalide')
                else:
                    question.markdown_text = required_data[0]
                    question.requested_role = required_data[1]
                    question.save()

        else:
            messages.error(request, u'Formulaire invalide')

    return render_to_response(
        'entreprise.html',
        {
            'request': request,
            'enterprise': enterprise,
            'reviews': reviews,
            'questions': questions,
            'contacts': contacts
        }, context_instance=RequestContext(request))


@login_required
def delete_review(request, review_id):
    """
    Deletes a given review

    :param request: request object
    :param review_id: id of the review
    """

    review = get_object_or_404(Review, id=review_id)
    enterprise_id = review.enterprise.id

    if request.user != review.user:
        messages.error(request, u'Impossible de supprimer la critique')
    else:
        review.delete()

    return HttpResponseRedirect(reverse_lazy(
        'jobs.views.enterprise', args=(enterprise_id,)))


@login_required
def delete_question(request, question_id):
    """
    Deletes a given question

    :param request: request object
    :param question_id: id of the question
    """

    question = get_object_or_404(Question, id=question_id)
    enterprise_id = question.enterprise.id

    if request.user != question.user:
        messages.error(request, u'Impossible de supprimer la question')
    else:
        question.delete()

    return HttpResponseRedirect(reverse_lazy(
        'jobs.views.enterprise', args=(enterprise_id,)))

jobs/templates/ajouter.html
{% extends "base2.html" %}


{% block template-specific-css %}
<link href="/media/css/associations.css" rel="stylesheet">
<link href="/media/css/jobs.css" rel="stylesheet">
{% endblock %}


{% block content-block %}

<div class="container event-body">

    <div class="page-header">
        <h2 class="text-center">Ajouter à la base de données d'entreprises</h2>
    </div>

    {% if messages %}
    {% for message in messages %}
        <div class="callout callout-danger">
            <h4>{{ message }}</h4>
        </div>
    {% endfor %}
    {% endif %}
    
    <form enctype="multipart/form-data" method="POST" action="">
        <fieldset>
            {% csrf_token %}

            <div class="form-group">
                <label for="id_enterprise">Entreprise</label>

                <select class="form-control" id="id_enterprise" name="enterprise">
                    {% for enterprise in enterprises %}
                    <option value="{{ enterprise.id }}">{{ enterprise.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">L'entreprise n'est pas dans la liste ?</a>
                        </h4>
                    </div>
                
                    <div id="collapseOne" class="panel-collapse collapse">
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="id_other_name">Nom</label>
                                <input class="form-control" id="id_other_name" name="other_name">
                            </div>

                            <div class="form-group">
                                <label for="id_other_location">Localisation (Ville, Pays)</label>
                                <input class="form-control" id="id_other_location" name="other_location">
                            </div>

                            <div class="form-group">
                                <label for="id_other_description">Description (<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown</a> autorisé)</label>
                                <textarea class="form-control" style="resize: none" id="id_other_description" name="other_description" rows="6"></textarea>
                            </div>

                            <div class="form-group">
                                <label for="id_other_website">Site internet</label>
                                <input class="form-control" id="id_other_website" type="url" name="other_website">
                            </div>

                            <div class="form-group">
                                <label for="id_other_logo">Logo</label>
                                <input class="form-control" id="id_other_logo"  type="file" name="other_logo">
                            </div>

                            <i>Tous les champs sont obligatoires</i>

                        </div>
                    </div>
                </div>
            </div>

            <div class="form-actions pull-right">
                <button class="btn btn-primary" type="submit">Valider</button>
                <a class="btn btn-default" href="{% url 'jobs.views.jobs' %}">Annuler</a>
            </div>
        </fieldset>
    </form>

</div>
{% endblock %}


{% block template-specific-js %}

{% endblock %}

jobs/templates/editer.html
{% extends "base2.html" %}


{% block template-specific-css %}
<link href="/media/css/associations.css" rel="stylesheet">
<link href="/media/css/jobs.css" rel="stylesheet">
{% endblock %}


{% block content-block %}

<div class="container event-body">

    <div class="page-header">
        <h2 class="text-center">Ajouter des données pour {{ enterprise.name }}</h2>
    </div>
    
    <div class="col-md-6 col-sm-12">
        <div id="review_error" class="hide">
            <div class="callout callout-danger">
                <h4>Un des champs est vide ou incorrect.</h4>
            </div>
        </div>

        <div id="review_success" class="hide">
            <div class="callout callout-success">
                <h4>Critique postée avec succès.</h4>
            </div>
        </div>

        <form enctype="multipart/form-data" method="POST" action="" id="review_form">
            <fieldset>
                <legend>Ajouter une critique</legend>

                <div class="form-group">
                    <label for="id_review">Texte de la critique (<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown</a> autorisé)</label>
                    <textarea class="form-control" style="resize: none" id="id_review" rows="6"></textarea>                    
                </div>

                <div class="form-group">
                    <label for="id_wage">Salaire</label>
                    <input class="form-control" id="id_wage" type="text">               
                </div>

                <div class="form-group">
                    <label for="id_year">Année d'étude</label>

                    <select class="form-control" id="id_year">
                        {% for year in years %}
                        <option value="{{ year.0 }}">{{ year.1 }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-actions">
                    <input class="btn btn-primary" type="submit" value="Envoyer la critique">
                </div>
            </fieldset>
        </form>
    </div>

    <div class="col-md-6 col-sm-12">
        <div id="question_error" class="hide">
            <div class="callout callout-danger">
                <h4>Un des champs est vide ou incorrect.</h4>
            </div>
        </div>

        <div id="question_success" class="hide">
            <div class="callout callout-success">
                <h4>Question postée avec succès.</h4>
            </div>
        </div>

        <form enctype="multipart/form-data" method="POST" action="" id="question_form">
            <fieldset>
                <legend>Ajouter une question d'entretien</legend>

                <div class="form-group">
                    <label for="id_role">Entretien pour un poste de</label>
                    <input class="form-control" id="id_role" type="text">    
                </div>

                <div class="form-group">
                    <label for="id_question">Question (<a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">Markdown</a> autorisé)</label>
                    <textarea class="form-control" style="resize: none" id="id_question" rows="6"></textarea>                    
                </div>

                <div class="form-actions">
                    <input class="btn btn-primary" type="submit" value="Envoyer la question">
                </div>
            </fieldset>
        </form>
    </div>

</div>
{% endblock %}


{% block template-specific-js %}

<script>
    $('#review_form').submit(function(event) {
        event.preventDefault();

        posting = $.post($(this).attr('action'), {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
            'type': 'review',
            'review': $('#id_review').val(),
            'wage': $('#id_wage').val(),
            'year': $('#id_year').val()
        });

        posting.done(function(data) {
            if (data.success) {
                $('#review_error').addClass('hide');
                $('#review_success').removeClass('hide');

                $('#id_review').val('');
                $('#id_wage').val('');
            } else {
                $('#review_error').removeClass('hide');
                $('#review_success').addClass('hide');
            }
        });
    });

    $('#question_form').submit(function(event) {
        event.preventDefault();

        posting = $.post($(this).attr('action'), {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
            'type': 'question',
            'question': $('#id_question').val(),
            'role': $('#id_role').val()
        });

        posting.done(function(data) {
            if (data.success) {
                $('#question_error').addClass('hide');
                $('#question_success').removeClass('hide');

                $('#id_question').val('');
            } else {
                $('#question_error').removeClass('hide');
                $('#question_success').addClass('hide');
            }
        });
    });
</script>

{% endblock %}

jobs/templates/entreprises.html
{% extends "base2.html" %}


{% block template-specific-css %}
<link href="/media/css/associations.css" rel="stylesheet">
{% endblock %}


{% block content-block %}

<div class="container container-on-top">

    <div class="page-header">
        {% if request.user.is_authenticated %}
        <a role="button" class="btn btn-info pull-right" href="{% url 'jobs.views.add_entry' %}">
            <i class="fa fa-plus"></i> Ajouter
        </a>
        {% endif %}

        <h2 class="text-center">Entreprises</h2>
    </div>

    <div class="well">
        {% for enterprise in enterprises %}

        {% if forloop.counter0|divisibleby:4 %}
        <div class="row">
        {% endif %}

            <div class="col-md-3 col-sm-6">
                <div class="thumbnail mini-thumbnail">
                    <img src="{{ enterprise.logo.url }}" alt="enterprise logo">
                    <div class="caption">
                        <a href="{% url 'jobs.views.enterprise' enterprise.id %}">
                          <h4>{{ enterprise.name }}</h4>
                        </a>
                    </div>
                </div>
            </div>

        {% if forloop.counter|divisibleby:4 or forloop.last %}
        </div>
        {% endif %}

        {% empty %}
        Il n'y a aucune entreprise pour le moment !
        {% endfor %}

        <div class="clearfix"></div>
    </div>

</div>
{% endblock %}


{% block template-specific-js %}

{% endblock %}